### ISSUE TITLE
[remocon] Monitor remocon executables better

### ISSUE THREAD

**Issue by bit-pirate** [robotics-in-concert/rocon_qt_gui#110]
This is a follow-up of the remocon-related issues in robotics-in-concert/rocon_tools#40.

`_start_global_executable_interaction` should monitor, if the start of a new process/thread was successful.

**Comment by stonier** [comment]
What is the symptom and case where this is awry?

**Comment by bit-pirate** [comment]
Check the linked issue, where the case and symptoms are explained in detail. Let me know, if you need more information than provided there.

**Comment by bit-pirate** [comment]
Quick summary: 

There are cases - e.g. roslauncher wrongly identified as global script - in which the process can't be started. Since the above method uses Popen, which starts a new thread. Catching the related exception is not trivial. E.g. I was only able to catch the exception inside the `rocon_python_tools.popen._run_in_thread` method (not even in the classes `**init**).

**Comment by stonier** [comment]
The handling of non-existant launchers, rosrunnables and filenames has been moved `a priori`.

There are process listeners (InteractiveClient._process_listeners) which monitor a process and catch it when it dies so the remocon can react, so that ....should cover everything else.

Leaving this open for now though...see if we can catch cases where it doesn't cover everything else.

**Comment by stonier** [comment]
Reopen if something else comes up.
